// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rh_admin.Repositorys;

namespace rh_admin.Migrations
{
    [DbContext(typeof(FuncionarioContext))]
    [Migration("20210227184850_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("rh_admin.Funcionario", b =>
                {
                    b.Property<string>("NumeroChapa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("NumeroChapa");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            NumeroChapa = "11",
                            DataCadastro = new DateTime(2021, 2, 27, 15, 48, 50, 199, DateTimeKind.Local).AddTicks(7183),
                            Email = "teste@gmail.com",
                            Nome = "teste",
                            Sobrenome = "Testoso"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
